import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  metadataBase: new URL("https://cbt-app-94ip.vercel.app"),
  title: "God's Way CBT App",
  description: "God's Way Application",
  icons: [
    { rel: "icon", url: "/school_logos.png" },
    { rel: "shortcut icon", url: "/school_logos.png" },
    { rel: "apple-touch-icon", url: "/school_logos.png" }
  ]
  // openGraph: {
  //   title: "God's Way CBT App",
  //   description: "God's Way CBT App by OLA",
  //   images: [
  //     {
  //       url: "/school_logos.png",
  //       width: 1200,
  //       height: 630
  //     }
  //   ]
  // },
  // twitter: {
  //   card: "summary_large_image",
  //   title: "God's Way CBT App",
  //   description: "God's Way CBT App by OLA",
  //   images: ["/school_logos.png"]
  // }
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div></div>
        {children}
      </body>
    </html>
  )
}





// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { SessionProvider } from "next-auth/react";
// import SessionProviderWrapper from "@/components/SessionProviderWrapper";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <SessionProviderWrapper>{children}</SessionProviderWrapper>
//       </body>
//     </html>
//   );
// }
